export default function Head() {
  return (
    <>
      <title>Shopping List</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name='viewport'
        content='initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover'
      />
      <link rel="icon" href="/favicon.ico" />
      <link rel="manifest" href="/manifest.json" />
    </>
  )
}